version: '3'

services:
  # Service Symfony
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    
  # Service MySQL
  mysql-gth3:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: GTH3

volumes:
  database_data:
  ###< doctrine/doctrine-bundle ###
