controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

event_create:
    path: /event/create
    controller: App\Controller\EventController::create

event_show:
    path: /event/show/{id}
    controller: App\Controller\EventController::show